version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guest_microservice_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: guest_microservice_db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: guest_service
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
